sudo: false
language: python

python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"

install:
    - pip install tox>=1.8 flake8

script:
    - tox -e \
      $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
    - flake8

notifications:
  email: false
